### ISSUE TITLE
Convex to Ball?

### ISSUE THREAD

**Issue by viperscape** [sebcrozet/ncollide#107]
Is it possible to create a Ball from the Convex shape? I see you can calculate using bounding_sphere but this seems expensive to do every time for a convex shape that does not change. Bounding_sphere takes a positional argument, which isn't static in this case. Thanks

**Comment by sebcrozet** [comment]
If I understand correctly your question, all you have to do is to compute the bounding sphere once, and update its position whenever your convex shape moves. In other words, this would be:

```rust
let shape = Convex::new(your_vertices);

// Compute the bounding sphere in the shape's local frame.
// (Any transformation other than the identity will do here, as long as you take this in account in the next updates.)
let bs = bounding_volume::bounding_sphere(&shape, &Identity::new());

// Now if your object moved by a transformation `m` of type, say, Iso2.
let updated_bs = BoundingSphere::new(m * *bs.center(), bs.radius());

// Or, if your object moved by some translation `v` of type, say, Vec2.
let updated_bs = BoundingSphere::new(*bs.center() + v, bs.radius());
```

So every time your convex shape is affected by a rigid transformation, its bounding sphere's center is affected by the very same transformation.

**Comment by viperscape** [comment]
Oh this makes total sense! Thank you, this is very helpful
