### ISSUE TITLE
Raycast example without identity mat?

### ISSUE THREAD

**Issue by viperscape** [sebcrozet/ncollide#110]
[example](https://github.com/sebcrozet/ncollide/blob/master/examples/solid_ray_cast3d.rs) shows how to raycast with an identity matrix. When I take this and supply my own matrix I receive compile errors.

```rust
error: the trait `nalgebra::traits::geometry::Transform<nalgebra::structs::pnt::Pnt3<f32>>` is not implemented for the type `nalgebra::structs::mat::Mat4<f32>` [E0277]
```

I don't understand what instead I should supply other than a Mat4, or Iso3.to_homogeneous() which is how I derive my Mat4. Please advise, thank you

**Comment by sebcrozet** [comment]
You should use the iso3 directly instead. A `Mat4` does not have enough geometric properties to allow an efficient ray-cast implementation for most type of objects (e.g. a Mat4 could contain things like shearing or be a projection which modifies significantly the transformed object original shape). The Iso3 on the other hand is guaranteed to be a composition of rotation + translation only.

**Comment by viperscape** [comment]
So I tried that originally, I get this error:

```rust
error: the trait `nalgebra::traits::geometry::Transform<nalgebra::structs::pnt::Pnt3<f32>>` is not implemented for the type `&nalgebra::structs::iso::Iso3<f32>` [E0277]
```

How ever I just tried again, as Iso3 and not &Iso3 and it works. Thanks! I should have looked at the definition more closely
