### ISSUE TITLE
unwrap() failing in CollisionWorld::update

### ISSUE THREAD

**Issue by jminer** [sebcrozet/ncollide#135]
I'm using ncollide 0.9.1 for a game I'm working on. When I added it to the game, but it panicked the first time I called `CollisionWorld::update`. [This unwrap](https://github.com/sebcrozet/ncollide/blob/a2dcc55a64b99eab8e45065b56060b89d10199f4/ncollide_pipeline/broad_phase/dbvt_broad_phase.rs#L299) was failing:

~~~
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:325
stack backtrace:
...
   9:        0x10b45845c - core::panicking::panic::h4bb1497076d04ab9
  10:        0x10b1e131a - _<std..option..Option<T>>::unwrap::h0aa4d6aefa249378
  11:        0x10b1e1588 - _<ncollide..broad_phase..DBVTBroadPhase<P, BV, T> as ncollide..broad_phase..BroadPhase<P, BV, T>>::deferred_set_bounding_volume::h1740a03bc351d7da
  12:        0x10b205837 - _<ncollide..world..CollisionWorld<P, M, T>>::perform_position_update::h3c35fb203d71c603
  13:        0x10b2055b4 - _<ncollide..world..CollisionWorld<P, M, T>>::update::h179c1d093094f3e5
  14:        0x10b2005ea - alphabot::server::ServerState::update::hb707929512f7229b
~~~

After checking my usage and reading some of ncollide's source, I finally realized that the reason may be that I wasn't calling `CollisionWorld::update` between when I `add`ed an object and when I called `CollisionWorld::deferred_set_position`. I made that change, and it doesn't panic anymore.

I didn't know that was needed, and if either ncollide handled it automatically or panicked with an error message telling me what was wrong, it would have saved me a lot of time.

**Comment by sebcrozet** [comment]
That's right, the addition is deferred. I should name the collision object addition method `deferred_add` instead of just `add` to reflect this.

Though the fact that this specific unwrap panics is a bug: it should panic on the CollisionWorld directly, not on the broad phase.

**Comment by sebcrozet** [comment]
The renaming from `.add` to `.deferred_add` will be effective starting with ncollide 0.10.0 (which will not be published just now).

**Comment by jminer** [comment]
Renaming `add` is something I hadn't thought of. If it were called `deferred_add`, that probably would have clued me in. Both of those changes sound great. Thanks!
