### ISSUE TITLE
The User Guide doesn't indicate the version of nalgebra that is required

### ISSUE THREAD

**Issue by radix** [sebcrozet/ncollide#138]
It seems nalgebra 0.10.x has made some incompatible changes that prevent the examples from working, And the [Getting Started](http://ncollide.org/getting_started/) page does not indicate an nalgebra version to depend on in the Cargo.toml, though it is required to add a dependency to run the examples. My experience was:

1. try to run example, get error about no nalgebra dependency
2. look up latest version of nalgebra, add `nalgebra = "0.10.*"` as per nalgebra documentation
3. try to run examples and get very confusing errors about traits not being implemented

so I think this can be fixed by just updating the Getting Started page to indicate `nalgebra = "0.9.*"`.

**Comment by Kerollmops** [comment]
[I git the same problem](http://users.nphysics.org/t/strange-error-with-nalgebra-vector3/46). I think it needs a fix or an explanation.

**Comment by sebcrozet** [comment]
That's right. Only the version 0.9 of nalgebra is supported at the moment (ncollide will be updated as soon as I am done with [nalgebra v0.11](https://github.com/sebcrozet/nalgebra/issues/207).

I've made the user guide clearer.
