### ISSUE TITLE
Documentation appears to be out of sync with nalgebra 0.11.2

### ISSUE THREAD

**Issue by projektir** [sebcrozet/ncollide#149]
Was looking at this page in particular: http://ncollide.org/rustdoc/ncollide/shape/struct.Ball.html

It is referencing a nalgebra trait called Translate which is a broken link: http://nalgebra.org/doc/nalgebra/traits/geometry/trait.Translate.html

When clicking `[src]`, the code doesn't correspond to what's actually in the repo.

It seems that the documentation for ncollide may need to be regenerated.

**Comment by sebcrozet** [comment]
Yes, the ncollide rustdoc documentation was outdated. It should be OK now.
