### ISSUE TITLE
Cuboid + Cylinder inconsistency, intersecting, but no contact

### ISSUE THREAD

**Issue by MichaelShaw** [sebcrozet/ncollide#157]
I've found a cylinder + cuboid that have a distance of 0, proximity is "Intersecting", but no contact is being generated regardless of prediction.

It's somewhat stable on the x axis in that I still get no contact if I vary the x-coords slightly. If I remove 60.0 from the z translations though, it returns a contact.

    use nalgebra as na;
    use ncollide as nc;
    use nalgebra::{Isometry3, Vector3};
    use ncollide::shape::{Cuboid, Cylinder};
    
    let cyl = Cylinder::new(0.925, 0.5);
    let cyl_at = Isometry3::new(Vector3::new(10.97, 0.925, 61.02), na::zero());
    let cuboid = Cuboid::new(Vector3::new(0.05, 0.75, 0.5));
    let cuboid_at = Isometry3::new(Vector3::new(11.50, 0.75, 60.5), na::zero());
    
    let distance = nc::query::distance(&cyl_at, &cyl,
                                       &cuboid_at, &cuboid);
    
    let proximity = nc::query::proximity(&cyl_at, &cyl,
                                         &cuboid_at, &cuboid,
                                         0.1);
    
    let contact = nc::query::contact(&cyl_at, &cyl,
                                     &cuboid_at, &cuboid,
                                     10.0);
    
    println!("distance -> {:?}", distance);
    println!("proximity -> {:?}", proximity);
    println!("contact -> {:?}", contact);

**Comment by sebcrozet** [comment]
This is a bug. When two objects are touching or penetrating, an iterative algorithms is executed to compute the penetration vector. The algorithm currently implemented is not extremely stable so it [breaks](https://github.com/sebcrozet/ncollide/blob/master/ncollide_geometry/query/contacts_internal/support_map_against_support_map.rs#L90) on some corner cases unfortunately… The only solution here is to implement a more accurate algorithm such as the EPA.

**Comment by ChristianBeilschmidt** [comment]
Is this a bug of the algorithm or of the implementation? It seems this behavior occurs more often when the two object centers are really close.

By the way, is there a specialized function for checking the distance between two cuboids?

**Comment by j-rock** [comment]
I believe I might be bitten by the same thing.

Scenario: Cuboid falling onto a flat TriMesh. No matter how big I scale up the cuboid in the vertical axis, there will be a gap of ~0.08 between the two objects.

![untitled](https://user-images.githubusercontent.com/4583364/39024894-a755c634-4411-11e8-9e8f-c2423487e6ff.png)

@sebcrozet, can you show me what needs to be done here?

**Comment by j-rock** [comment]
It appears that you have already implemented the EPA algorithm.

Perhaps this is a separate bug? When I iterate through the [world.collision_world().contacts()](http://ncollide.org/rustdoc/ncollide_pipeline/world/struct.CollisionWorld.html#method.contacts), the [Contact data](http://ncollide.org/rustdoc/ncollide_geometry/query/struct.Contact.html) reflects a penetration depth of -0.08 (+/- some error).

Is it normal to have negative penetration depths such as these? (I would think that a negative penetration depth would reflect that two bodies are not yet touching.)

**Comment by j-rock** [comment]
@sebcrozet Ah, thank you so much, that was a wonderful explanation!

**Comment by sebcrozet** [comment]
Now that EPA is implemented, this issue no longer happens.
