### ISSUE TITLE
Is there a way to use a Collision World in a Mutex?

### ISSUE THREAD

**Issue by radix** [sebcrozet/ncollide#162]
Hi, I'm trying to use `World` in a multithreaded app with `Mutex`, but I can't, because the types involved don't implement `Send`.

I see that DBVT uses Rc, and I know the usual way to solve that is to switch it to using `Arc`, but I presume that you don't want to use `Arc` by default for performance reasons. Is there any other way I can work around this problem?

**Comment by thiolliere** [comment]
I want to use ncollide with specs (an entity component system library), for that I need CollisionWorld to implement Sync and Send. 
I know the DBVT doesn't implement Send nor Sync.
If I use a broad phase that implements those marker would it be OK ? or there is lot more to do ?

**Comment by thiolliere** [comment]
after some experiment it seems that: 
If we force some trait to inherit Send and Sync then the only structure of ncollide that must be changed to implement Send and Sync is the DBVT

see https://github.com/thiolliere/ncollide/commit/ab5e7e2c8d498aca996bc79f514b8412eb0a0648

**Comment by sebcrozet** [comment]
I'm currently working on this issue as part of the redesign of nphysics to make it ECS-compatible. On the ncollide-side, the main issue is indeed with the `DBVT` and the `DBVTBroadPhase` which use `Rc<RefCell>`.

I have a version of ncollide that works with specs on the [send_sync](https://github.com/sebcrozet/ncollide/tree/send_sync) branch. It contains a `Send + Sync` version of the [DBVT](https://github.com/sebcrozet/ncollide/blob/send_sync/ncollide_geometry/partitioning/dbvt2.rs) (called DBVT2 for now) and of the [DBVTBroadPhase](https://github.com/sebcrozet/ncollide/blob/send_sync/ncollide_pipeline/broad_phase/dbvt_broad_phase2.rs) but it is still fairly untested.

**Comment by radix** [comment]
@sebcrozet very cool! I suppose that CollisionWorld also needs to be updated to use this new DBVT2 (or perhaps parameterized to allow accepting the DBVT as an argument?) Or are you just planning on replacing the DBVT with what you currently have in DBVT2?

**Comment by sebcrozet** [comment]
@radix  `CollisionWorld` is already updated on the `send_sync` branch to use the `DBVT2`. So it should be specs-compatible and mutex-compatible already.

In the end the old Rc-based DBVT will be removed in favor of the new one.

**Comment by sebcrozet** [comment]
The CollisionWorld is now Send+Sync on the new version of ncollide (which is now released as the `ncollide2d` and `ncollide3d` crates as mentioned in this [post](https://www.patreon.com/posts/nphysics-0-8-0-18689882)).
