### ISSUE TITLE
Storing a ShapeHandle in a struct.

### ISSUE THREAD

**Issue by dkushner** [sebcrozet/ncollide#176]
Currently trying to integrate the masterpiece that is nphysics into my component-entity style game engine and having difficulty finding a way to wrap the `ShapeHandle` instance in a struct that fits the trait bounds required by `RigidBody::new()`. Currently my struct looks like:

```rust
#[derive(Clone)]
pub struct RigidBody {
    shape: ShapeHandle<na::Point3<f64>, na::Isometry3<f64>>,
    body_type: BodyType,
}
```

But when I attempt to pass this shape handle to create a new `RigidBody` I get the following:
```
error[E0277]: the trait bound `ncollide::shape::ShapeHandle<nalgebra::Point<f64, nalgebra::U3>, nalgebra::Isometry<f64, nalgebra::U3, nalgebra::Unit<nalgebra::Quaternion<f64>>>>: nphysics3d::volumetric::Volumetric<_, nalgebra::geometry::point::PointBase<_, nalgebra::core::dimension::U3, nalgebra::core::matrix_array::MatrixArray<_, nalgebra::core::dimension::U3, nalgebra::core::dimension::U1>>, nalgebra::core::matrix::Matrix<_, nalgebra::core::dimension::U3, nalgebra::core::dimension::U3, nalgebra::core::matrix_array::MatrixArray<_, nalgebra::core::dimension::U3, nalgebra::core::dimension::U3>>>` is not satisfied
  --> src/physics/physics.rs:72:25
   |
72 |                         Body::new_dynamic(body.shape.clone(), dens, res, fric)
   |                         ^^^^^^^^^^^^^^^^^ the trait `nphysics3d::volumetric::Volumetric<_, nalgebra::geometry::point::PointBase<_, nalgebra::core::dimension::U3, nalgebra::core::matrix_array::MatrixArray<_, nalgebra::core::dimension::U3, nalgebra::core::dimension::U1>>, nalgebra::core::matrix::Matrix<_, nalgebra::core::dimension::U3, nalgebra::core::dimension::U3, nalgebra::core::matrix_array::MatrixArray<_, nalgebra::core::dimension::U3, nalgebra::core::dimension::U3>>>` is not implemented for `ncollide::shape::ShapeHandle<nalgebra::Point<f64, nalgebra::U3>, nalgebra::Isometry<f64, nalgebra::U3, nalgebra::Unit<nalgebra::Quaternion<f64>>>>`
```

Which makes sense as I have not ensured that the specific incarnation of ShapeHandle I am using fits the bounds of that function. What I am curious about is the best approach to get around this. Will I simply have to parameterize my struct in order to ensure these same bounds are met?

**Comment by sebcrozet** [comment]
Assuming the `Body` type here is an alias for the nphysics' `RigidBody` type, the issue here is that `::new_dynamic` expects to be given a concrete shape type that implements some traits, including `Volumetric` (i.e. not a trait-object which is what `ShapeHandle` are).

So if you which to create a rigid body from a `ShapeHandle`, you have to use the [Body::new](https://docs.rs/nphysics3d/0.7.2/nphysics3d/object/struct.RigidBody.html#method.new) method. It won't automatically compute the mass properties of the shape so they must be input to the `new` function.

**Comment by dkushner** [comment]
@sebcrozet: Works perfectly, thanks!
