### ISSUE TITLE
Assertion failure in EPA2

### ISSUE THREAD

**Issue by leod** [sebcrozet/ncollide#181]
Since EPA was introduced recently, I have been noticing some strange behavior in my simple 2D simulation, which involves getting contact pairs for two rectangles. Sometimes EPA2 does not converge, or it causes a panic:
```
thread 'main' panicked at 'assertion failed: neg_dist <= gjk::eps_tol()', ncollide_geometry/query/algorithms/epa2.rs:26:9
```
I'm using 0881d357a9b59dd0c4829965b6659615692fe6c6 of the `send_sync` branch.

I've reduced the assertion failure to the following test case. It moves a square cuboid into a long wall cuboid and, if there is a contact, it applies the contact normal to the square's position (in a bit of an arbitrary way). The test case is somewhat convoluted since I don't know what exactly causes the error:
https://gist.github.com/leod/f6830274539834098973c6c35527d9d3

I get the error after 174668 iterations of the `for` loop. Backtrace:
```
thread 'main' panicked at 'assertion failed: neg_dist <= gjk::eps_tol()', ncollide_geometry/query/algorithms/epa2.rs:26:9
stack backtrace:
..
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: <ncollide_geometry::query::algorithms::epa2::FaceId<N>>::new
             at ./<panic macros>:3
   7: <ncollide_geometry::query::algorithms::epa2::EPA2<P>>::project_origin
             at ./ncollide_geometry/query/algorithms/epa2.rs:202
   8: ncollide_geometry::query::algorithms::epa2::closest_points
             at ./ncollide_geometry/query/algorithms/epa2.rs:292
   9: ncollide_geometry::query::contacts_internal::support_map_against_support_map::support_map_against_support_map_with_params
             at ./ncollide_geometry/query/contacts_internal/support_map_against_support_map.rs:127
  10: <ncollide_pipeline::narrow_phase::contact_generator::support_map_support_map_contact_generator::SupportMapSupportMapContactGenerator<P, M, S> as ncollide_pipeline::narrow_phase::contact_generator::contact_generator::ContactGenerator<P, M>>::update
             at ./ncollide_pipeline/narrow_phase/contact_generator/support_map_support_map_contact_generator.rs:69
  11: <ncollide_pipeline::narrow_phase::contact_generator::incremental_contact_manifold_generator::IncrementalContactManifoldGenerator<P, M, CD>>::add_new_contacts
             at ./ncollide_pipeline/narrow_phase/contact_generator/incremental_contact_manifold_generator.rs:110
  12: <ncollide_pipeline::narrow_phase::contact_generator::incremental_contact_manifold_generator::IncrementalContactManifoldGenerator<P, M, CD> as ncollide_pipeline::narrow_phase::contact_generator::contact_generator::ContactGenerator<P, M>>::update
             at ./ncollide_pipeline/narrow_phase/contact_generator/incremental_contact_manifold_generator.rs:185
  13: <ncollide_pipeline::narrow_phase::contact_generator::one_shot_contact_manifold_generator::OneShotContactManifoldGenerator<P, M, CD> as ncollide_pipeline::narrow_phase::contact_generator::contact_generator::ContactGenerator<P, M>>::update
             at ./ncollide_pipeline/narrow_phase/contact_generator/one_shot_contact_manifold_generator.rs:102
  14: epa_test::main
             at examples/epa_test.rs:29
..
```
Is this error to be expected due to the way I am using `ncollide` here, or is it a bug in `ncollide`?

**Comment by sebcrozet** [comment]
Your use of `ncollide` is correct. The issue here most likely originates from numerical inaccuracies on the GJK algorithm (run before the EPA) caused by the fact that one cuboid is significantly larger than the other.

If think the right approach for fixing this issue is to allow the epa to fail, i.e., return `None` instead of paniccing. In case of failure, we would just run a fallback algorithm to handle those rare cases of numerical issues.

**Comment by leod** [comment]
Do you have an algorithm in mind for the fallback? I might try working on this.

Also, a naive question from someone who hasn't worked much on contact detection: would it make sense to special case the contact algorithms for certain cases, e.g. for cuboid-cuboid or rect-rect? Or do you want to avoid that? I'm thinking that those cases could work without iterative algorithms.

**Comment by sebcrozet** [comment]
An algorithm for the fallback is already implemented (it is what we used before switching to EPA). So I will fix this issue today.

> Also, a naive question from someone who hasn't worked much on contact detection: would it make sense to special case the contact algorithms for certain cases, e.g. for cuboid-cuboid or rect-rect? Or do you want to avoid that? I'm thinking that those cases could work without iterative algorithms.

Yes, it would totally make sense. I've not done this yet because of lack of time, but dedicated algorithms for cuboid-cuboid would be very useful. This is one of the reasons `nphysics` (which uses `ncollide`) is still slower than, e.g., Bullet which has dedicated contact generation for pairs of cuboids.

**Comment by sebcrozet** [comment]
After further testing, it appears the issue here is mostly due to computations that are inherently prone to numerical errors (catastrophic cancellation) inside of the point-projection-on-triangle algorithm. Thus I am going to use more stable operations that seem to be enough to handle your test case. Feel free to re-open this issue if you encounter other similar issues again.

**Comment by leod** [comment]
Thank you. This has definitely reduced how often the error occurs, but I can still trigger it with my test case, for example by increasing the size of `cuboid_b` from `300.0` to `800.0`. This is not a big problem for me, since I can just segment the cuboid into multiple smaller objects. I think it still makes sense to re-open the issue, though.

**Comment by leod** [comment]
Revisiting this issue, in case anyone else runs into similar problems: I think the reason that I have been getting this assertion error so often is specifically because I moved two objects to positions where they were right at the *boundary of collision / no collision*.

This happened in my position-based collision solver. Now, I've changed the collision resolution such that colliding objects are moved further apart by some `delta` (in my case `0.1`), meaning that they no longer overlap once the constraint is solved, which seems like a reasonable thing to do anyway. I've been getting the assertion error a lot less with this `delta`, though it does still happen occasionally.

**Comment by magnonellie** [comment]
Could we possibly reopen this? I'm encountering this issue quite a bit in my application and it doesn't really make sense that it should just crash once it does occur.

**Comment by sebcrozet** [comment]
@magnonellie I've removed the assertions so it should no longer crash. However, it does not handles the failing case very well as the the algorithm will still attempt to compute the penetration depth. I will have to take a closer look at this later, but at least it should work fine most of the time and won't crash when it doesn't.

**Comment by magnonellie** [comment]
@sebcrozet Awesome! Thanks a lot for all your hard work. :heart:
