### ISSUE TITLE
is sparse vec wrong ?

### ISSUE THREAD

**Issue by thiolliere** [sebcrozet/ncollide#190]
https://github.com/sebcrozet/ncollide/blob/master/ncollide_utils/data/sparse_vec.rs#L49-L55

It seems to me that removing a data should add its id to the free vector and it is not the case

**Comment by sebcrozet** [comment]
Thank you for finding this bug.
`SparceVec` no longer exists on the new `ncollide2d` and `ncollide3d` crates so I am closing this.
