### ISSUE TITLE
New crates.io release

### ISSUE THREAD

**Issue by hirschenberger** [sebcrozet/ncollide#208]
Hi, 

the last version that's availabe in crates.io is `0.14.1`. When will there be a new release or do I have to use github as source?

BTW: The README also says to use:

```
[dependencies]
ncollide = "0.16"
```
which does not exist.

Greetings hirsch

**Comment by thiolliere** [comment]
ncollide2d and ncollide3d are 0.16.0 on crates.io though

**Comment by sebcrozet** [comment]
@hirschenberger Hi! The readme is misleading. `ncollide` is deprecated so `ncollide2d` and `ncollide3d` should be used instead.

I will update the readme to reflect that.

**Comment by hirschenberger** [comment]
Oh, I totally missed the 2d-3d split. This really makes the generic signatures easier.
