### ISSUE TITLE
Time of impact does not work as intended (?)

### ISSUE THREAD

**Issue by thepotatocoder** [sebcrozet/ncollide#214]
I've been trying to use ncollide2d in my project recently, but this stunned me.
The following snippet works as intended (there is a possible collision):
```
let shape1 = Cuboid::new(Vector2::new(1.0, 1.0));
let shape2 = Cuboid::new(Vector2::new(1.0, 1.0));

let pos1 = Isometry2::new(Vector2::new(0.0, 0.0), zero());
let pos2 = Isometry2::new(Vector2::new(10.0, 0.0), zero());

let vel1 = Vector2::new(2.0, 0.0);
let vel2 = Vector2::new(0.0, 0.0);

let toi = time_of_impact(&pos1, &vel1, &shape1, &pos2, &vel2, &shape2);
assert!(toi.is_some());
```
However the following does not (no possible collision, assertion fails):
```
let shape1 = Cuboid::new(Vector2::new(1.0, 1.0));
let shape2 = Cuboid::new(Vector2::new(1.0, 1.5));

let pos1 = Isometry2::new(Vector2::new(0.0, 0.0), zero());
let pos2 = Isometry2::new(Vector2::new(10.0, 0.0), zero());

let vel1 = Vector2::new(1.0, 0.0);
let vel2 = Vector2::new(0.0, 0.0);

let toi = query::time_of_impact(&pos1, &vel1, &shape1, &pos2, &vel2, &shape2);
assert!(toi.is_some());
```
As I understand it, this is what is represented:
First scenario:
![geogebra-export](https://user-images.githubusercontent.com/19825279/42707630-bda175d8-86d2-11e8-94a2-f684dbc5eade.png)
Second scenario:
![geogebra-export2](https://user-images.githubusercontent.com/19825279/42707631-bdc58edc-86d2-11e8-8760-340e3bbe2329.png)

Why does changing one shape's height in the slightest makes the `toi == None`?
Is there something I'm interpreting wrong?
Thanks for your time.

**Comment by sebcrozet** [comment]
Thanks for the detailed explanation of your issue! This is a bug that appears to be a consequence of #205.

**Comment by thepotatocoder** [comment]
@sebcrozet How can I circumvent this? I only need to handle collisions of 2d rectangles.

**Comment by sebcrozet** [comment]
Right now I am not sure there is a robust workaround. I will try to fix it this week-end!
Maybe one way of avoiding this is to apply a very small rotation to one of the rectangles when performing the time-of-impact query. But that seems sketchy.

**Comment by thepotatocoder** [comment]
@sebcrozet Hmm, might work, I'll see if I can use that, then. Thanks for helping out and good luck with fixing that!

**Comment by sebcrozet** [comment]
@thepotatocoder This is fixed on the `master` branch. I am running out of time right now, so I won't publish to crates.io just now, but you may try the `master` branch in the mean time (if this is possible for you)
