### ISSUE TITLE
Build times are huge

### ISSUE THREAD

**Issue by bfops** [sebcrozet/ncollide#48]
`ncollide` takes almost two minutes to build on my machine. It's got a *whole lot* of features. It also takes a while to `git clone`. Any chance it could be split into multiple repos?

**Comment by bfops** [comment]
That seems like a great design, and I'm not personally opposed to `ncollide_entities` and `ncollide_queries` merging. Unless it's possible to break up `Shape` in some way that lets it be used for `Compound`s in `ncollide_entities` and also for queries in `ncollide_queries`?

**Comment by sebcrozet** [comment]
As a first pass, I am going to use another, rather restrictive, option that allows us to keep `entities` and `queries` as two separate crates.

The `Shape` trait will be removed (I never liked it anyway) in favor of another trait that doesn't inherit from any feature but uses a trick to remove the main thing that makes the library so slow to compile (i-e. the number of trait and data structure instantiated by the compiler that is quadratic in the number of shape type). As a downside, this will prevent the user from using its own shape types with a `Compound`.

To do this properly and allow the user to use its own shape type, we would need some sort of introspection that tells whether or not some feature is implemented for the given shape instance. The fact that vtables are not part of a structure instance makes this _non-trivial_.
