### ISSUE TITLE
trait `core::marker::Reflect` is not implemented for the type `T`

### ISSUE THREAD

**Issue by yohanesu** [sebcrozet/ncollide#71]
Hi

I get this error when building nphysics with
[a@JMBA-DEV nphysics]$ cargo --version
cargo 0.0.1-pre-nightly (72f2af1 2015-03-29) (built 2015-03-29)
[a@JMBA-DEV nphysics]$ rustc --version
rustc 1.0.0-dev (d8be84eb4 2015-03-29) (built 2015-03-30)

Compiling ncollide_utils v0.1.0 (https://github.com/sebcrozet/ncollide#70b20217)
/home/mirama/.cargo/git/checkouts/ncollide-7d59428b74aca038/master/ncollide_utils/any_private.rs:13:9: 13:24 error: the trait `core::marker::Reflect` is not implemented for the type `T` [E0277]
/home/mirama/.cargo/git/checkouts/ncollide-7d59428b74aca038/master/ncollide_utils/any_private.rs:13         TypeId::of::<T>()
                                                                                                            ^~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `ncollide_utils`.

**Comment by sebcrozet** [comment]
Hi. I’m unable to reproduce your bug as the current version of rustc ICEs when it tries to compile the library.

I’ll come back to this issue as soon as #72 is fixed.
