### ISSUE TITLE
Does not compile with recent versions of rustc.

### ISSUE THREAD

**Issue by sebcrozet** [sebcrozet/ncollide#72]
`ncollide` currently fails to compile with recent versions of `rustc`. The main reason is the removal of `#![old_impl_check]`. This makes the use of associated types mandatory at some places.

While I started some work on `nalgebra` and `ncollide` to fix this, I ran into an ICE − rust-lang/rust#24179. Also, rust-lang/rust#23595 prevents us from fixing `ncollide` without using associated types on `nalgebra`.

I have the feeling there is no other solutions than waiting for the compiler bug to be fixed.

**Comment by wackywendell** [comment]
Is there any change with this? The two rust bugs look thorny, and its really unfortunate that even with Rust 1.0 out, this still isn't working.

**Comment by sebcrozet** [comment]
Yes, I believe I am almost done fixing everything. I worked around those bug at a price of bad syntax at some places (e.g. things like `<P::Vect as Vect>::Scalar` to identify the scalar type associated by a point `P` where Ithink that bug-free associated types could allow me to write `P::Scalar` directly). Hopefully I will manage to land all those fixes at the end of the week!

**Comment by wackywendell** [comment]
HURRAY!!!
