### ISSUE TITLE
Docs outdated? 

### ISSUE THREAD

**Issue by Binero** [sebcrozet/ncollide#83]
The docs on http://ncollide.org/ seem to be outdated. For example, there seems to be no `GeomGeomDispatcher` in the project, while the docs clearly mention it here: http://ncollide.org/contact_determination/narrow_phase.html

**Comment by sebcrozet** [comment]
Yes, the hand-written documentation is very outdated, I did not have the time to update it since the last major change of `ncollide`'s infrastructure. The core mathematical concepts remain the same but the types and/or their type parameters changed a lot since then.

The cargo-generated doc is up-to-date (but a bit incomplete), though : http://ncollide.org/doc/ncollide/

**Comment by meh** [comment]
Are there any examples anywhere that can replace the hand-written documentation for the time being?

**Comment by sebcrozet** [comment]
Well unfortunately all the existing examples are those from the documentation and are outdated as well. You will find them all [there](https://github.com/sebcrozet/ncollide/tree/gh-pages/src). Though I am almost done updating `nrays` to the latest version of rust, so I should be able to start fixing `ncollide`-related documentation soon. I will use this thread to give updates about my progress on updating the docs.

In the mean time, you can dig into `nrays` or `nphysics`. However they both use advanced features of `ncollide` so they might not be of much help if you need something concise about one specific feature.

You may also open "issues" like #88 . In the future I might just end up creating a forum for this kind of queries.

**Comment by meh** [comment]
I think I'll wait for the time being, fortunately I can work on other sides of the game engine before I implement collision detection.

As a note, it might be useful to add a note on the website that the docs are outdated, I spent quite some time trying to figure out if I was dumb, the generated rustdoc was broken, or the examples were out of date, then I found this issue :panda_face:

**Comment by acolley** [comment]
Are the user docs version controlled anywhere? I'm sure myself and others would be happy to submit pull requests to keep them updated if we find they're out of date or lacking in a particular area.

**Comment by sebcrozet** [comment]
Yes, the documentation (written in markdown) is versioned on the [gh-pages](https://github.com/sebcrozet/ncollide/tree/gh-pages) branch in this repository. Also, the corresponding web pages are generated using [GitBook](https://www.gitbook.com/). Contributions are very welcome !

**Comment by sebcrozet** [comment]
Closing this in favor of #93.
