### ISSUE TITLE
Problems using bounding_sphere() method on Ball.

### ISSUE THREAD

**Issue by acolley** [sebcrozet/ncollide#84]
I am attempting to compile some code using the Ball shape and obtain its Bounding Sphere using the `bounding_sphere()` method.

However I'm having trouble importing the correct trait in order to use this method. I'm trying to use the `HasBoundingSphere` trait as this appears to be where the method is defined but it's not able to resolve it correctly.

Here is a minimal example that demonstrates the issue:

```rust
extern crate nalgebra as na;
extern crate ncollide;

use ncollide::shape::{Ball};
use ncollide::bounding_volume::{HasBoundingSphere};

fn main() {
    let ball = Ball::new(1.0);
    ball.bounding_sphere(na::one());
}
```

Am I doing something monumentally stupid here? (I suspect I am). Any help would be much appreciated.

**Comment by sebcrozet** [comment]
Mmh, that's weird. I will take a closer look on this as soon as I can. The strange part is that it works when used with an auxiliary function like:

```rust
extern crate num;
extern crate nalgebra as na;
extern crate ncollide;

use num::One;
use na::Iso2;
use ncollide::shape::{Ball};
use ncollide::math::{Point};
use ncollide::bounding_volume::{HasBoundingSphere, BoundingSphere};

fn doit<T: HasBoundingSphere<P, M>, P: Point, M: One>(t: &T) -> BoundingSphere<P> {
    t.bounding_sphere(&na::one::<M>())
}

fn main() {
    let ball = Ball::new(1.0);
    doit::<_, _, Iso2<f32>>(&ball);
}
```

**Comment by sebcrozet** [comment]
Okay, so I don't think you are doing anything stupid here!

I believe this has something to do with the compiler not being able to infer all the types on the implementation of `HasBoundingSphere` for `BoundingSphere`. The only alternative I see for now is to create an auxiliary function (just as I did on my previous post):

```rust
extern crate num;
extern crate nalgebra as na;
extern crate ncollide;

use na::Iso2;
use ncollide::shape::Ball;
use ncollide::math::Point;
use ncollide::bounding_volume::{HasBoundingSphere, BoundingSphere};

fn bounding_sphere<T: HasBoundingSphere<P, M>, P: Point, M>(t: &T, m: &M) -> BoundingSphere<P> {
    t.bounding_sphere(m)
}

fn main() {
    let ball = Ball::new(1.0);
    bounding_sphere(&ball, &na::one::<Iso2<f32>>());
}
```

Surprisingly, this does compile while the following code does not (even if I have the feeling the compiler has the same amount of type information in both situations):

```rust
extern crate nalgebra as na;
extern crate ncollide;

use na::Iso2;
use ncollide::shape::{Ball};
use ncollide::bounding_volume::{HasBoundingSphere};

fn main() {
    let ball = Ball::new(1.0);
    ball.bounding_sphere(na::one::<Iso2<f32>>());
}
```

I think what needs to be done here is to declare this kind of auxiliary function on `ncollide` directly to help the compiler resolve the types correctly (and output a more sensible error message if some type annotations are needed).

**Comment by acolley** [comment]
Ah that does make sense. I agree that the compiler error was not particularly helpful in tracking down the issue though.

Thanks for the help, I will make use of the helper function as a solution for the time being.
