### ISSUE TITLE
Update the documentations.

### ISSUE THREAD

**Issue by sebcrozet** [sebcrozet/ncollide#93]
Now is a good time to update the documentations. Here is the list of tasks that need to be done:
  - [x] Move the examples from the `gh_pages` branch `src` folder to the `master` branch `examples` folder. This will help keeping them up-to-date because cargo will build them automatically whenever a `cargo test` is run.
  - [x] Upload the latest version of the output of `cargo doc` (must be done by me)
  - [x] Make the README clearer about how to contribute to the project and its documentation (currently described [on the guide](http://ncollide.org/how_to_contribute/index.html)).
  - [x] Update the guide on [ncollide.com](ncollide.org).

The last item can be split into several tasks as well:
  - [x] If methods or modules have been renamed, reflect this on the doc.
  - [x] Explain how `ncollide` is composed of several other `ncollide_foobar` crates.
  - [x] The `Getting Started` page must be completely rewritten.
  - [x] The differentiation DSL has been removed. Remove the related section on chapter 7.
  - [x] Make the examples download links point directly to their file on the github repo.
  - [x] The `Volumetric` trait has been removed. Remove the related examples on chapter 2.2; and the trait description on chapter 2.
  - [x] Talk about the new features added since then (e.g. the free functions to compute the TOI, contact points, the Repr inspection system, etc.)

Initiated by #83.

**Comment by sebcrozet** [comment]
I am currently working on fixing the examples.

**Comment by Kerosene2000** [comment]
[Ncollide/CollisionWorld](http://ncollide.org/doc/ncollide/world/struct.CollisionWorld.html) needs a complete documentation too ([CollisionWorld source code](https://github.com/sebcrozet/ncollide/blob/master/ncollide_pipeline/world/collision_world.rs)).

**Comment by sebcrozet** [comment]
This is strange because the `CollisionWorld` already has a complete documentation. Though it seems that rustdoc does not list them correctly.

**Comment by sebcrozet** [comment]
The new website is now [live](http://ncollide.org)!

**Comment by Kerosene2000** [comment]
Ho ! that's a beautiful new website 😄 GG !
